[package]
name = "tiny_gp_lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_assertions = "1.4.0"
rand = "0.7"
structopt = "0.3"
