[package]
name = "tiny_gp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
structopt = "0.3"
num-traits = "0.2"
num-derive = "0.2"
